# Generated by Django 4.2 on 2023-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', ' Puplished')], default='DF', max_length=5),
        ),
    ]
